---
  - name: AuditD | Install packages
    apt: pkg="auditd" state="present"
    retries: 3
    register: auditd_install_result
    until: auditd_install_result is not failed
    become: yes
    tags:
      - auditd

  - name: AuditD | Patch /etc/audit/auditd.conf with default props
    lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      insertafter: "{{ item.insertafter | default('EOF') }}"
    with_items: "{{ auditd_conf_default_props | default([]) }}"
    become: yes
    tags:
      - auditd

  - name: AuditD | Patch /etc/audit/auditd.conf with custom props
    lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      insertafter: "{{ item.insertafter | default('EOF') }}"
    with_items: "{{ auditd_conf_props | default([]) }}"
    become: yes
    tags:
      - auditd

  - name: AuditD |  Restart service
    service: name=auditd state=restarted enabled=yes
    become: yes
    when: docker_test is not defined
    tags:
      - auditd
